version: 2.0
jobs:
  build_clang:
    docker:
      - image: ethanlmiller/clang7python3classes
    steps:
      - checkout
      # - run: mkdir -p build && cd build
      - run: clang -o main main.cpp
      - run: ./main

  build_okannen_gcc_latest:
    docker:
      - image: okannen/gcc-10
    steps:
      - checkout
      # - run: mkdir -p build && cd build
      - run: g++ -o main main.cpp -std=c++17
      - run: ./main

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_clang
      - build_okannen_gcc_latest
