version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      # - run: mkdir -p build && cd build
      - run: g++ -o main main.cpp -std=c++14
      - run: ./main
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      # - run: mkdir -p build && cd build
      - run: g++ -o main main.cpp -std=c++17
      - run: ./main
